### ISSUE TITLE
Replacing the title and description in package.json

### ISSUE THREAD

**Issue by newtonkiragu** [malcolmkiano/exp#2]
The script is not able to replace the title and description in `package.json` and `packagelock.json` issuing the following error instead:
```bash
sed: 1: "package-lock.json": extra characters at the end of p command
sed: 1: "package.json": extra characters at the end of p command
sed: 1: "package.json": extra characters at the end of p command
```
Expected result:
replace title and description in `package.json` and `packagelock.json`.

How to reproduce the error:
Run the script `rc.sh`

**Comment by malcolmkiano** [comment]
I wasn't able to recreate the issue here, but after some investigation, I've found that there is a difference in the way the `sed` command is run on MacOS versus any other environment.

I've made a change with reference to [this post on StackOverflow](https://stackoverflow.com/questions/2320564/sed-i-command-for-in-place-editing-to-work-with-both-gnu-sed-and-bsd-osx). 

Let me know if this works for you so I can close this out 😄

**Comment by newtonkiragu** [comment]
It works well now. 👍
